name: Ruby

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.2.0'

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Install Firefox and Geckodriver
      run: |
        sudo apt-get update
        sudo apt-get install -y firefox
        wget https://github.com/mozilla/geckodriver/releases/download/v0.33.0/geckodriver-v0.33.0-linux64.tar.gz
        tar -xvzf geckodriver-v0.33.0-linux64.tar.gz
        sudo chmod +x geckodriver
        sudo mv geckodriver /usr/local/bin/
    - name: Run the default task
      run: bundle exec rake
